# Generated by Django 2.1 on 2018-08-16 13:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('comments_stauts', models.CharField(max_length=20)),
                ('comments_time', models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 26, 19, 518445, tzinfo=utc))),
                ('comments_author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=256)),
                ('contents', models.TextField()),
                ('initial_time', models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 26, 19, 517621, tzinfo=utc))),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 26, 19, 517689, tzinfo=utc))),
                ('next_approver', models.CharField(default=None, max_length=20)),
                ('process_serial_num', models.CharField(default='20180816132619', max_length=128)),
                ('level', models.CharField(max_length=10)),
                ('status', models.CharField(default='agree', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('real_name', models.CharField(default=None, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OAsysterm.Position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='processes',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processcomments',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OAsysterm.Processes'),
        ),
    ]
