# Generated by Django 2.1 on 2018-08-16 13:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OAsysterm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcomments',
            name='comments_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 26, 56, 779164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='processes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processes',
            name='initial_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 26, 56, 777667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='processes',
            name='process_serial_num',
            field=models.CharField(default='20180816132656', max_length=128),
        ),
        migrations.AlterField(
            model_name='processes',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 26, 56, 777734, tzinfo=utc)),
        ),
    ]
